prefix = "."
dataset = "news"
corpus = "line.toml"
index = "idx"

stop-words = "stopwords.txt"

[ranker]
method = "bm25"
k1 = 1.2
b = 0.75
k3 = 500

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"
