stop-words = "./data/lemur-stopwords.txt"
function-words = "./data/function-words.txt"
punctuation = "./data/sentence-boundaries/sentence-punctuation.txt"
start-exceptions = "./data/sentence-boundaries/sentence-start-exceptions.txt"
end-exceptions = "./data/sentence-boundaries/sentence-end-exceptions.txt"

prefix = "."
dataset = "news"
corpus = "line.toml"
index = "idx"


[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"