corpus = "line.toml"
dataset = "news"
prefix = "."
end-exceptions = "./data/sentence-boundaries/sentence-end-exceptions.txt"
punctuation = "./data/sentence-boundaries/sentence-punctuation.txt"
function-words = "./data/function-words.txt"
index = "idx"
start-exceptions = "./data/sentence-boundaries/sentence-start-exceptions.txt"
stop-words = "./data/lemur-stopwords.txt"
[[analyzers]]
	filter = "default-unigram-chain"
	ngram = 1
	method = "ngram-word"
